version: "3.9"
services:
  web:
    build: .
    volumes:
      - .:/bizchat
    image: bizchat:latest
    command: bundle exec rails s -u puma -p 5000 -b '0.0.0.0'
    env_file:
      - '.env'
    ports:
      - "5000:5000"
    depends_on:
      - redis
  redis:
    image: 'redis:5-alpine'
    command: redis-server